// AUTO-GENERATED — do not edit. Run `pnpm codegen`
// Generated by openapi-typescript from /openapi.json

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service liveness check
         * @description Return service status, API version, and the underlying py2dataiku version.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert Python code to a Dataiku flow (synchronous)
         * @description Convert Python code to a DataikuFlow.
         *
         *     - **mode=rule** (default): AST-based, offline, fast.
         *     - **mode=llm**: LLM-assisted, requires `ANTHROPIC_API_KEY` or `OPENAI_API_KEY`
         *       set in the server environment. Max 30-second wall-clock timeout.
         *
         *     Errors in the py2dataiku hierarchy are mapped to RFC 7807 problem+json.
         */
        post: operations["post_convert_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all 37 Dataiku recipe types
         * @description Return catalog entries for all 37 RecipeType values.
         *
         *     Response is cached for 60 seconds (public, max-age=60).
         */
        get: operations["get_recipes_catalog_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/processors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dataiku Prepare processors
         * @description Return catalog entries for Prepare processors (up to 122).
         *
         *     Optional filters: `q` (name/description substring) and `category` (exact match).
         *     Response is cached for 60 seconds.
         */
        get: operations["get_processors_catalog_processors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/processors/{processor_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single processor catalog entry by type
         * @description Return the catalog entry for a single processor type.
         *
         *     `processor_type` should be the DSS canonical name (e.g. `ColumnRenamer`).
         *     Returns 404 if the type is not in the catalog.
         */
        get: operations["get_processor_catalog_processors__processor_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute the per-node diff between two flows
         * @description Compare two flows by recipe name (the node id) and return added/removed/changed.
         *
         *     - **added**: recipe present in B but not in A.
         *     - **removed**: recipe present in A but not in B.
         *     - **changed**: recipe present in both with a different ``type`` or
         *       different settings/steps.
         */
        post: operations["post_diff_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute a complexity score for a flow
         * @description Compute the complexity score from a flow payload.
         *
         *     The flow is hydrated into a real ``DataikuFlow`` via ``from_dict`` so
         *     the FlowGraph metrics computed by ``score_flow`` are accurate.
         */
        post: operations["post_score_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ColumnSchemaModel
         * @description Mirrors ColumnSchema.to_dict().
         */
        ColumnSchemaModel: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Nullable
             * @default true
             */
            nullable: boolean;
            /** Default */
            default?: unknown;
            /** Format */
            format?: string | null;
        };
        /**
         * ComplexityScore
         * @description Flow complexity metrics derived from FlowGraph analysis.
         */
        ComplexityScore: {
            /**
             * Recipe Count
             * @description Total number of recipes
             */
            recipe_count: number;
            /**
             * Processor Count
             * @description Total prepare steps across all PREPARE recipes
             */
            processor_count: number;
            /**
             * Max Depth
             * @description Longest path from root to leaf (node hops)
             */
            max_depth: number;
            /**
             * Fan Out Max
             * @description Maximum out-degree of any single node
             */
            fan_out_max: number;
            /**
             * Complexity
             * @description Composite complexity score [0, ∞)
             */
            complexity: number;
            /**
             * Cost Estimate
             * @description Estimated LLM cost in USD (LLM mode only)
             */
            cost_estimate?: number | null;
        };
        /**
         * ConvertMode
         * @description Conversion mode: rule-based AST or LLM-assisted.
         * @enum {string}
         */
        ConvertMode: "rule" | "llm";
        /**
         * ConvertOptions
         * @description Optional per-request conversion options.
         */
        ConvertOptions: {
            /**
             * Provider
             * @description LLM provider (llm mode only)
             */
            provider?: ("anthropic" | "openai") | null;
            /**
             * Model
             * @description LLM model name override
             */
            model?: string | null;
            /**
             * Temperature
             * @description LLM temperature
             */
            temperature?: number | null;
            /**
             * Optimize
             * @description Run flow optimizer after conversion
             * @default true
             */
            optimize: boolean;
            /**
             * Max Code Size Bytes
             * @description Maximum allowed code size in bytes
             * @default 262144
             */
            max_code_size_bytes: number;
        };
        /**
         * ConvertRequest
         * @description Request body for POST /convert.
         */
        ConvertRequest: {
            /**
             * Code
             * @description Python source code to convert
             */
            code: string;
            /**
             * @description Conversion mode
             * @default rule
             */
            mode: components["schemas"]["ConvertMode"];
            options?: components["schemas"]["ConvertOptions"] | null;
        };
        /**
         * ConvertResponse
         * @description Response body from POST /convert.
         */
        ConvertResponse: {
            flow: components["schemas"]["DataikuFlowModel"];
            score: components["schemas"]["ComplexityScore"];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * DataikuDatasetModel
         * @description Mirrors DataikuDataset.to_dict() exactly.
         */
        DataikuDatasetModel: {
            /** Name */
            name: string;
            type: components["schemas"]["DatasetTypeEnum"];
            /** @default Filesystem */
            connection_type: components["schemas"]["DatasetConnectionTypeEnum"];
            /** Schema */
            schema?: components["schemas"]["ColumnSchemaModel"][];
            /** Source Variable */
            source_variable?: string | null;
            /** Source Line */
            source_line?: number | null;
            /** Notes */
            notes?: string[];
        };
        /**
         * DataikuFlowModel
         * @description Mirrors DataikuFlow.to_dict() shape exactly.
         *
         *     Validates that all recipe inputs/outputs reference datasets that exist
         *     in the datasets list.
         */
        DataikuFlowModel: {
            /**
             * Flow Name
             * @default converted_flow
             */
            flow_name: string;
            /** Generated From */
            generated_from?: string | null;
            /** Generation Timestamp */
            generation_timestamp?: string | null;
            /**
             * Total Recipes
             * @default 0
             */
            total_recipes: number;
            /**
             * Total Datasets
             * @default 0
             */
            total_datasets: number;
            /** Datasets */
            datasets?: components["schemas"]["DataikuDatasetModel"][];
            /** Recipes */
            recipes?: components["schemas"]["DataikuRecipeModel"][];
            /** Optimization Notes */
            optimization_notes?: string[];
            /** Recommendations */
            recommendations?: components["schemas"]["FlowRecommendationModel"][];
            /** Zones */
            zones?: components["schemas"]["FlowZoneModel"][];
        };
        /**
         * DataikuRecipeModel
         * @description Mirrors DataikuRecipe.to_dict() shape.
         *
         *     py-iku's to_dict() inlines recipe-type-specific settings via to_display_dict()
         *     rather than nesting them under a 'settings' key. Those fields pass through via
         *     `extra="allow"`.
         *
         *     The `settings` field is declared here as Optional so all 12 RecipeSettings
         *     subclass schemas are registered in the OpenAPI component registry. In practice
         *     it will be None for flows produced by py-iku's to_dict(), but callers that
         *     construct recipes directly may populate it.
         */
        DataikuRecipeModel: {
            /** Name */
            name: string;
            type: components["schemas"]["RecipeTypeEnum"];
            /** Inputs */
            inputs?: string[];
            /** Outputs */
            outputs?: string[];
            /** Source Lines */
            source_lines?: number[];
            /** Notes */
            notes?: string[];
            /**
             * Settings
             * @description Composed recipe settings (discriminated union over 12 subclasses). Not populated by py-iku to_dict(); present here to expose the full settings schema contract in /openapi.json.
             */
            settings?: (components["schemas"]["PrepareSettingsModel"] | components["schemas"]["GroupingSettingsModel"] | components["schemas"]["JoinSettingsModel"] | components["schemas"]["WindowSettingsModel"] | components["schemas"]["SamplingSettingsModel"] | components["schemas"]["SplitSettingsModel"] | components["schemas"]["SortSettingsModel"] | components["schemas"]["TopNSettingsModel"] | components["schemas"]["DistinctSettingsModel"] | components["schemas"]["StackSettingsModel"] | components["schemas"]["PythonSettingsModel"] | components["schemas"]["PivotSettingsModel"]) | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DatasetConnectionTypeEnum
         * @description Dataset connection types — mirrors DatasetConnectionType enum values.
         * @enum {string}
         */
        DatasetConnectionTypeEnum: "Filesystem" | "PostgreSQL" | "MySQL" | "BigQuery" | "Snowflake" | "Redshift" | "S3" | "GCS" | "Azure" | "HDFS" | "ManagedFolder" | "MongoDB" | "Elasticsearch";
        /**
         * DatasetTypeEnum
         * @description Dataset types — mirrors DatasetType enum values.
         * @enum {string}
         */
        DatasetTypeEnum: "input" | "intermediate" | "output";
        /**
         * DiffRequest
         * @description Request body for POST /diff.
         */
        DiffRequest: {
            /** @description The 'before' flow (e.g., rule output) */
            a: components["schemas"]["DataikuFlowModel"];
            /** @description The 'after' flow (e.g., LLM output) */
            b: components["schemas"]["DataikuFlowModel"];
        };
        /**
         * DiffResponse
         * @description Response body for POST /diff.
         */
        DiffResponse: {
            /** Added */
            added?: components["schemas"]["NodeDiff"][];
            /** Removed */
            removed?: components["schemas"]["NodeDiff"][];
            /** Changed */
            changed?: components["schemas"]["NodeDiff"][];
        };
        /**
         * DistinctSettingsModel
         * @description Mirrors DistinctSettings.to_dict(): computeCount.
         */
        DistinctSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "distinct";
            /**
             * Computecount
             * @default false
             */
            computeCount: boolean;
        };
        /**
         * FlowRecommendationModel
         * @description Mirrors FlowRecommendation.to_dict().
         */
        FlowRecommendationModel: {
            /** Type */
            type: string;
            /** Priority */
            priority: string;
            /** Message */
            message: string;
            /** Impact */
            impact?: string | null;
            /** Action */
            action?: string | null;
            /** Source Lines */
            source_lines?: number[];
        };
        /**
         * FlowZoneModel
         * @description Mirrors FlowZone.to_dict().
         */
        FlowZoneModel: {
            /** Name */
            name: string;
            /**
             * Color
             * @default #4b96e6
             */
            color: string;
            /** Datasets */
            datasets?: string[];
            /** Recipes */
            recipes?: string[];
        };
        /**
         * GroupingSettingsModel
         * @description Mirrors GroupingSettings.to_display_dict(): keys + aggregations.
         */
        GroupingSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "grouping";
            /** Keys */
            keys?: string[];
            /** Aggregations */
            aggregations?: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Py Iku Version */
            py_iku_version: string;
        };
        /**
         * JoinSettingsModel
         * @description Mirrors JoinSettings.to_display_dict(): join_type, join_keys, selected_columns.
         */
        JoinSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "join";
            /**
             * Join Type
             * @default LEFT
             */
            join_type: string;
            /** Join Keys */
            join_keys?: {
                [key: string]: unknown;
            }[];
            /** Selected Columns */
            selected_columns?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * NodeDiff
         * @description A single per-node difference entry.
         *
         *     For ``added`` and ``removed`` entries ``diff`` is None. For ``changed`` entries
         *     ``diff`` enumerates which fields differ between A and B.
         */
        NodeDiff: {
            /**
             * Id
             * @description Recipe name used as the node id
             */
            id: string;
            /**
             * Recipe Type A
             * @description Recipe type in flow A (None when added in B)
             */
            recipe_type_a?: string | null;
            /**
             * Recipe Type B
             * @description Recipe type in flow B (None when removed from B)
             */
            recipe_type_b?: string | null;
            /**
             * Diff
             * @description When kind=changed: which fields differ ({field: {a, b}}).
             */
            diff?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PivotSettingsModel
         * @description Mirrors PivotSettings.to_dict(): rowColumns, columnColumn, valueColumn, aggregation.
         */
        PivotSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pivot";
            /** Rowcolumns */
            rowColumns?: string[];
            /**
             * Columncolumn
             * @default
             */
            columnColumn: string;
            /**
             * Valuecolumn
             * @default
             */
            valueColumn: string;
            /**
             * Aggregation
             * @default SUM
             */
            aggregation: string;
        };
        /**
         * PrepareSettingsModel
         * @description Mirrors PrepareSettings.to_display_dict(): steps + step_count.
         */
        PrepareSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "prepare";
            /** Steps */
            steps?: components["schemas"]["PrepareStepModel"][];
            /**
             * Step Count
             * @default 0
             */
            step_count: number;
        };
        /**
         * PrepareStepModel
         * @description Mirrors PrepareStep.to_dict() output.
         *
         *     Fields: metaType, type (processor DSS string), disabled, params, name.
         */
        PrepareStepModel: {
            /**
             * Metatype
             * @description PROCESSOR or GROUP
             * @default PROCESSOR
             */
            metaType: string;
            /**
             * Type
             * @description DSS processor type string (e.g. 'ColumnRenamer')
             */
            type: string;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Name
             * @description Optional step label
             */
            name?: string | null;
        };
        /**
         * ProcessorCatalogEntry
         * @description A single entry in the processor catalog (from ProcessorCatalog.get_processor).
         */
        ProcessorCatalogEntry: {
            /**
             * Type
             * @description ProcessorType enum value
             */
            type: components["schemas"]["ProcessorTypeEnum"] | string;
            /**
             * Name
             * @description DSS processor name (canonical)
             */
            name: string;
            /**
             * Category
             * @description Processor category
             */
            category: string;
            /**
             * Description
             * @description Short description
             */
            description: string;
            /** Required Params */
            required_params?: string[];
            /** Optional Params */
            optional_params?: string[];
            /**
             * Examples
             * @description Example parameter values
             */
            examples?: {
                [key: string]: unknown;
            };
        };
        /**
         * ProcessorTypeEnum
         * @description All 122 unique ProcessorType values from py2dataiku.
         * @enum {string}
         */
        ProcessorTypeEnum: "ColumnRenamer" | "ColumnCopier" | "ColumnsSelector" | "ColumnReorder" | "ColumnsConcat" | "FillEmptyWithValue" | "RemoveRowsOnEmpty" | "UpDownFill" | "FillEmptyWithComputedValue" | "ImputeWithML" | "StringTransformer" | "Tokenizer" | "PatternExtract" | "FindReplace" | "ColumnsSplitter" | "HtmlStripper" | "MultiColumnFindReplace" | "Ngrammer" | "SimplifyText" | "StemText" | "LemmatizeText" | "LanguageDetector" | "SentimentAnalyzer" | "TextHasher" | "UnicodeNormalizer" | "URLParser" | "IPAddressParser" | "EmailDomainExtractor" | "PhoneFormatter" | "CountryNormalizer" | "UserAgentParser" | "NumericalTransformer" | "Round" | "NumberClipping" | "Binner" | "MeasureNormalize" | "TypeSetter" | "DateParser" | "DateFormatter" | "DateComponentExtractor" | "DateDifference" | "HolidaysComputer" | "TimezoneConverter" | "DateRangeClassifier" | "TimestampExtractor" | "FilterOnValue" | "FilterOnBadType" | "FilterOnFormula" | "FilterOnDateRange" | "FilterOnNumericRange" | "FilterOnMultipleValues" | "FilterOnNullNumeric" | "FilterOnGeoZone" | "FilterOnCustomCondition" | "FlagOnValue" | "FlagOnFormula" | "FlagOnBadType" | "FlagOnDateRange" | "FlagOnNumericRange" | "RemoveDuplicates" | "SortRows" | "SampleRows" | "ShuffleRows" | "CreateColumnWithGREL" | "Formula" | "MultiColumnFormula" | "ColumnPseudoAnonymizer" | "HashComputer" | "UUIDGenerator" | "LongTailGrouper" | "CategoricalEncoder" | "GeoPointCreator" | "GeoEncoder" | "GeoIPResolver" | "GeoDistanceCalculator" | "GeoPolygonMatcher" | "AddressParser" | "ReverseGeocoder" | "IfThenElse" | "SwitchCase" | "TranslateValues" | "ExtractWithJSONPath" | "SplitURL" | "FoldMultipleColumns" | "TransposeRowsToColumns" | "Unfold" | "Coalesce" | "FillColumn" | "ArraySplitter" | "ArrayJoiner" | "ArraySorter" | "ArrayUnfold" | "ArrayFold" | "ArrayElementExtractor" | "JSONFlattener" | "JSONExtractor" | "XMLExtractor" | "NestedProcessor" | "ProcessorGroup" | "PythonUDF";
        /**
         * PythonSettingsModel
         * @description Mirrors PythonSettings.to_dict(): code.
         */
        PythonSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "python";
            /**
             * Code
             * @default
             */
            code: string;
        };
        /**
         * RecipeCatalogEntry
         * @description A single entry in the recipe catalog.
         */
        RecipeCatalogEntry: {
            type: components["schemas"]["RecipeTypeEnum"];
            /**
             * Name
             * @description Human-readable recipe name
             */
            name: string;
            /**
             * Category
             * @description Recipe category (e.g. Visual, Code, ML)
             */
            category: string;
            /**
             * Icon
             * @description Unicode or ASCII icon character
             */
            icon: string;
            /**
             * Description
             * @description Short description of the recipe
             */
            description: string;
            /**
             * Pandas Examples
             * @description pandas patterns that map to this recipe
             */
            pandas_examples?: string[];
        };
        /**
         * RecipeTypeEnum
         * @description All 37 Dataiku DSS recipe types.
         * @enum {string}
         */
        RecipeTypeEnum: "prepare" | "sync" | "grouping" | "window" | "join" | "fuzzyjoin" | "geojoin" | "stack" | "split" | "sort" | "distinct" | "topn" | "pivot" | "sampling" | "download" | "generate_features" | "generate_statistics" | "push_to_editable" | "list_folder_contents" | "dynamic_repeat" | "extract_failed_rows" | "upsert" | "list_access" | "python" | "r" | "sql_script" | "hive" | "impala" | "spark_sql_query" | "pyspark" | "spark_scala" | "sparkr" | "shell" | "prediction_scoring" | "clustering_scoring" | "standalone_evaluation" | "ai_assistant_generate";
        /**
         * SamplingSettingsModel
         * @description Mirrors SamplingSettings.to_dict(): samplingMethod + sampleSize.
         */
        SamplingSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sampling";
            /**
             * Samplingmethod
             * @default RANDOM_FIXED_NB
             */
            samplingMethod: string;
            /** Samplesize */
            sampleSize?: number | null;
        };
        /**
         * SortSettingsModel
         * @description Mirrors SortSettings.to_dict(): sortColumns.
         */
        SortSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sort";
            /** Sortcolumns */
            sortColumns?: {
                [key: string]: string;
            }[];
        };
        /**
         * SplitSettingsModel
         * @description Mirrors SplitSettings.to_dict(): splitMode + condition.
         */
        SplitSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "split";
            /**
             * Splitmode
             * @default FILTER
             */
            splitMode: string;
            /**
             * Condition
             * @default
             */
            condition: string;
        };
        /**
         * StackSettingsModel
         * @description Mirrors StackSettings.to_dict(): mode.
         */
        StackSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stack";
            /**
             * Mode
             * @default UNION
             */
            mode: string;
        };
        /**
         * TopNSettingsModel
         * @description Mirrors TopNSettings.to_dict(): topN + rankingColumn.
         */
        TopNSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "topn";
            /**
             * Topn
             * @default 10
             */
            topN: number;
            /** Rankingcolumn */
            rankingColumn?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WindowSettingsModel
         * @description Mirrors WindowSettings.to_dict(): partitionColumns, orderColumns, aggregations.
         */
        WindowSettingsModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "window";
            /** Partitioncolumns */
            partitionColumns?: {
                [key: string]: string;
            }[];
            /** Ordercolumns */
            orderColumns?: {
                [key: string]: string;
            }[];
            /** Aggregations */
            aggregations?: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_convert_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResponse"];
                };
            };
            /** @description Invalid Python syntax */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Code exceeds max_code_size_bytes */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error or conversion failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error or configuration problem */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description LLM provider error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_recipes_catalog_recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeCatalogEntry"][];
                };
            };
        };
    };
    get_processors_catalog_processors_get: {
        parameters: {
            query?: {
                /** @description Filter by name or description substring */
                q?: string | null;
                /** @description Filter by exact category name */
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessorCatalogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_processor_catalog_processors__processor_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processor_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessorCatalogEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_diff_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_score_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataikuFlowModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplexityScore"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
