"""Generate a pytest integration test from a converted flow.

Given a flow dict and the source code that produced it, emit a self-contained
``test_<flow_name>.py`` that:

  - imports :mod:`py2dataiku`
  - re-runs ``convert(<source>)``
  - asserts the recipe-type sequence (in topological order)
  - asserts dataset name sets per kind (input/intermediate/output)
  - asserts the output recipe / dataset counts
  - optionally asserts column-lineage of named columns

The result is a single ``.py`` file the user drops into ``tests/`` —
re-runnable, version-controllable and CI-friendly.
"""

from __future__ import annotations

import json
import re
from typing import Any


def _safe_name(s: str) -> str:
    """Sanitize *s* into a valid Python identifier slug."""
    s = re.sub(r"[^A-Za-z0-9_]+", "_", s).strip("_") or "flow"
    if s[0].isdigit():
        s = f"_{s}"
    return s.lower()


def _recipe_type_sequence(flow: dict[str, Any]) -> list[str]:
    return [r.get("type") for r in flow.get("recipes") or [] if r.get("type")]


def _dataset_names_by_kind(flow: dict[str, Any]) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {"input": [], "intermediate": [], "output": []}
    for d in flow.get("datasets") or []:
        kind = d.get("type")
        name = d.get("name")
        if kind in out and isinstance(name, str):
            out[kind].append(name)
    for k in out:
        out[k] = sorted(out[k])
    return out


HEADER = '''"""Auto-generated integration test for the py-iku-converted flow.

Generated by py-iku Studio. Re-run this with::

    pytest -xvs {filename}

The test re-runs ``py2dataiku.convert`` on the original source and asserts
the resulting flow is shape-stable: same recipe-type sequence, same dataset
counts, same dataset names per kind. Column lineage assertions (when
included) verify the named columns still appear in upstream/downstream
edges.
"""
'''


BODY_TEMPLATE = '''
from __future__ import annotations

import pytest

from py2dataiku import convert


SOURCE = {source!r}

EXPECTED_RECIPE_TYPES = {recipe_types!r}
EXPECTED_DATASET_NAMES = {dataset_names!r}
EXPECTED_RECIPE_COUNT = {recipe_count}
EXPECTED_DATASET_COUNT = {dataset_count}


def _convert():
    return convert(SOURCE)


def test_recipe_type_sequence():
    """Recipe types appear in the same order as on the captured flow."""
    flow = _convert().to_dict()
    types = [r["type"] for r in flow["recipes"]]
    assert types == EXPECTED_RECIPE_TYPES, (
        f"Expected {{EXPECTED_RECIPE_TYPES!r}} but got {{types!r}}"
    )


def test_recipe_count():
    flow = _convert().to_dict()
    assert len(flow["recipes"]) == EXPECTED_RECIPE_COUNT


def test_dataset_count():
    flow = _convert().to_dict()
    assert len(flow["datasets"]) == EXPECTED_DATASET_COUNT


@pytest.mark.parametrize("kind", sorted(EXPECTED_DATASET_NAMES.keys()))
def test_dataset_names_by_kind(kind):
    flow = _convert().to_dict()
    actual = sorted(d["name"] for d in flow["datasets"] if d.get("type") == kind)
    expected = EXPECTED_DATASET_NAMES[kind]
    assert actual == expected, f"{{kind}} datasets drift: expected {{expected!r}} got {{actual!r}}"
'''


LINEAGE_TEMPLATE = '''

EXPECTED_LINEAGE_COLUMNS = {columns!r}


def test_column_lineage_present():
    """Each tracked column still appears somewhere in the flow's recipes."""
    flow = _convert().to_dict()
    seen = set()
    for r in flow["recipes"]:
        for s in r.get("steps") or []:
            params = s.get("params") or {{}}
            for k in ("column", "output_column", "new_column"):
                v = params.get(k)
                if isinstance(v, str):
                    seen.add(v)
            for renaming in params.get("renamings") or []:
                if isinstance(renaming, dict):
                    for kk in ("from", "to"):
                        vv = renaming.get(kk)
                        if isinstance(vv, str):
                            seen.add(vv)
            v = params.get("columns")
            if isinstance(v, list):
                for x in v:
                    if isinstance(x, str):
                        seen.add(x)
    for d in flow.get("datasets") or []:
        for c in d.get("schema") or []:
            if isinstance(c, dict) and isinstance(c.get("name"), str):
                seen.add(c["name"])
    missing = [c for c in EXPECTED_LINEAGE_COLUMNS if c not in seen]
    assert not missing, f"Lineage columns missing from flow: {{missing!r}}"
'''


def scaffold_test(
    *,
    flow: dict[str, Any],
    source: str,
    flow_name: str | None = None,
    track_columns: list[str] | None = None,
) -> tuple[str, str]:
    """Build a pytest module string for *flow* / *source*.

    Returns ``(filename, source_text)``. ``filename`` is suitable for use in
    ``Content-Disposition`` and as a file name on disk.
    """
    name = flow_name or flow.get("flow_name") or "flow"
    safe = _safe_name(str(name))
    filename = f"test_{safe}_integration.py"

    recipe_types = _recipe_type_sequence(flow)
    dataset_names = _dataset_names_by_kind(flow)
    recipe_count = len(flow.get("recipes") or [])
    dataset_count = len(flow.get("datasets") or [])

    body = BODY_TEMPLATE.format(
        source=source,
        recipe_types=recipe_types,
        dataset_names=dataset_names,
        recipe_count=recipe_count,
        dataset_count=dataset_count,
    )
    out = HEADER.format(filename=filename) + body
    if track_columns:
        out += LINEAGE_TEMPLATE.format(columns=list(track_columns))
    return filename, out


__all__ = ["scaffold_test"]
